//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRtbl
    {
        public IRtbl()
        {
            this.SSTables = new HashSet<SSTable>();
        }
    
        public int Req_Id { get; set; }
        public string Input_Req { get; set; }
    
        public virtual ICollection<SSTable> SSTables { get; set; }
    }
}
