//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSTable
    {
        public int Id { get; set; }
        public string SentencesSegmentation { get; set; }
        public Nullable<int> Req_Id { get; set; }
    
        public virtual IRtbl IRtbl { get; set; }
    }
}
