//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webweb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDD_POS
    {
        public tblDD_POS()
        {
            this.tblDDs = new HashSet<tblDD>();
        }
    
        public int ID { get; set; }
        public string POSTagging { get; set; }
        public string Word { get; set; }
        public Nullable<int> tblPOSS { get; set; }
        public Nullable<int> tblDD { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    
        public virtual tblPOSS tblPOSS1 { get; set; }
        public virtual ICollection<tblDD> tblDDs { get; set; }
    }
}
