//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webweb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDD
    {
        public int DD_Id { get; set; }
        public string Nouns { get; set; }
        public string Determinants { get; set; }
        public string Pronouns { get; set; }
        public string Verbs { get; set; }
        public string Adjectives { get; set; }
        public string Adverbs { get; set; }
        public string Articles { get; set; }
        public string Preposition { get; set; }
        public string Conjuctions { get; set; }
        public string Interjections { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual tblDD_POS tblDD_POS { get; set; }
    }
}
