//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webweb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParagraph
    {
        public tblParagraph()
        {
            this.tblSentences = new HashSet<tblSentence>();
        }
    
        public int ID { get; set; }
        public string Req_Text { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<tblSentence> tblSentences { get; set; }
    }
}
