//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webweb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWord
    {
        public tblWord()
        {
            this.tblPOSSes = new HashSet<tblPOSS>();
        }
    
        public int ID { get; set; }
        public string Word { get; set; }
        public Nullable<int> tblSentences_ID { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual tblSentence tblSentence { get; set; }
        public virtual ICollection<tblPOSS> tblPOSSes { get; set; }
    }
}
